// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/search-products.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/search-products.ts
var search_products_default = defineTool({
  name: "search_products",
  title: "Search products",
  description: "Search the APPAREL Co. catalog by name, category or keyword. Returns matching products with price, sizes and colors.",
  inputSchema: {
    query: z.string().trim().optional().describe("Free-text search against product name and description."),
    category: z.string().trim().optional().describe("Filter by category, e.g. t-shirts, hoodies, accessories."),
    limit: z.number().int().min(1).max(50).optional().describe("Maximum number of products to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, category, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("products").select("id, name, price, original_price, category, description, sizes, colors, featured, is_new, image_url").limit(limit ?? 20);
    if (category) q = q.eq("category", category);
    if (query) q = q.or(`name.ilike.%${query}%,description.ilike.%${query}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { products: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-product.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var get_product_default = defineTool2({
  name: "get_product",
  title: "Get product",
  description: "Fetch a single APPAREL Co. product by its ID, including price, description, sizes and colors.",
  inputSchema: {
    product_id: z2.string().trim().min(1).describe("The product's unique ID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ product_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("products").select("id, name, price, original_price, category, description, sizes, colors, featured, is_new, image_url").eq("id", product_id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: `No product found with ID ${product_id}` }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { product: data }
    };
  }
});

// src/lib/mcp/tools/list-my-orders.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var list_my_orders_default = defineTool3({
  name: "list_my_orders",
  title: "List my orders",
  description: "List the signed-in customer's own APPAREL Co. orders with status, totals and dates.",
  inputSchema: {
    limit: z3.number().int().min(1).max(50).optional().describe("Maximum number of orders to return (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("orders").select("id, status, total_amount, shipping_cost, created_at, email").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 10);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { orders: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-my-order.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var get_my_order_default = defineTool4({
  name: "get_my_order",
  title: "Get my order",
  description: "Fetch one of the signed-in customer's own orders by ID, including the purchased line items.",
  inputSchema: {
    order_id: z4.string().trim().min(1).describe("The order's unique ID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ order_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data: order, error } = await supabase.from("orders").select("id, status, total_amount, shipping_cost, shipping_address, created_at, email").eq("id", order_id).eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!order) return { content: [{ type: "text", text: `No order found with ID ${order_id}` }], isError: true };
    const { data: items, error: itemsError } = await supabase.from("order_items").select("*").eq("order_id", order_id);
    if (itemsError) return { content: [{ type: "text", text: itemsError.message }], isError: true };
    const payload = { ...order, items: items ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: { order: payload }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ldmstuidmzjdbdbognly";
var mcp_default = defineMcp({
  name: "apparel-co-launch",
  title: "APPAREL Co. Launch",
  version: "0.1.0",
  instructions: "Tools for the APPAREL Co. streetwear store. Use `search_products` and `get_product` to browse the catalog, and `list_my_orders` / `get_my_order` to look up the signed-in customer's own orders. Prices are in ZAR.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_products_default, get_product_default, list_my_orders_default, get_my_order_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
